export default [
    {
        path:'/home',
        label:'Home',
        children:[

        ]
    },
    {
        path:'/buy',
        label:'Buy',
        children:[
             {
                path:"/",
                label:"Apartments"
            },
        ]
    },
    {
        path:'/sell',
        label:'Sell',
        children:[
            {
                path:"/",
                label:"Apartments"
            },
        ]
    },
    {
        path:'/product',
        label:'Rent',
        children:[
            {
                path:"/",
                label:"Apartments"
            },
            {
                path:"/",
                label:"Villa"
            },
            {
                path:"/",
                label:"Penthouse"
            },
            {
                path:"/",
                label:"Town house copy"
            },
            {
                path:"/",
                label:"Plot"
            },
            {
                path:"/",
                label:"Loft & Duplex"
            },
            {
                path:"/",
                label:"Office"
            },
        ]
    },
    {
        path:'/property',
        label:'Properties',
        children:[]
    }
]